"""Agregando tablas de dashboards

Revision ID: 4e27382997cd
Revises: aa4e8a6c2244
Create Date: 2025-12-16 09:34:18.759285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e27382997cd'
down_revision = 'aa4e8a6c2244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discusiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discusion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_comentario', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discusion_id'], ['discusiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emprendedor_proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emprendedor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo_apoyo_buscado', sa.String(length=100), nullable=True),
    sa.Column('capital_requerido', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emprendedor_id'], ['emprendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresario_alianzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_oferta', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresario_id'], ['empresarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresario_mercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresario_id'], ['empresarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institucion_convocatorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.Column('publico_objetivo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institucion_noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('vistas', sa.Integer(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institucion_programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=True),
    sa.Column('cupos_totales', sa.Integer(), nullable=True),
    sa.Column('cupos_ocupados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('perfil_empresario')
    op.drop_table('perfil_inversionista')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_inversionista',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_fondo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tipo_inversion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('etapas_interes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('areas_interes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('perfil_inversionista_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('perfil_inversionista_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('perfil_inversionista_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('perfil_empresario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_empresa', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo_contribuyente', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('numero_documento_contribuyente', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nit', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('tamano', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('etapa', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sector_produccion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sector_transformacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sector_comercializacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('perfil_empresario_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('perfil_empresario_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('perfil_empresario_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('tipo_documento_personal', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('numero_documento_personal', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('numero_celular', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('terminos_aceptados', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('correo', name=op.f('user_correo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('numero_documento_personal', name=op.f('user_numero_documento_personal_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('institucion_programas')
    op.drop_table('institucion_noticias')
    op.drop_table('institucion_convocatorias')
    op.drop_table('empresario_mercado')
    op.drop_table('empresario_alianzas')
    op.drop_table('emprendedor_proyectos')
    op.drop_table('comentarios')
    op.drop_table('discusiones')
    # ### end Alembic commands ###
