"""Inicial

Revision ID: aa4e8a6c2244
Revises: 
Create Date: 2025-12-12 10:41:41.494653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4e8a6c2244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('tipo_perfil', sa.Enum('EMPRESARIO', 'EMPRENDEDOR', 'INVERSIONISTA', 'INSTITUCION', 'ADMIN', name='tipoperfil', native_enum=False), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprendedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=30), nullable=False),
    sa.Column('numero_celular', sa.String(length=15), nullable=False),
    sa.Column('programa_formacion', sa.String(length=150), nullable=False),
    sa.Column('titulo_proyecto', sa.String(length=150), nullable=False),
    sa.Column('descripcion_proyecto', sa.Text(), nullable=False),
    sa.Column('relacion_sector', sa.String(length=250), nullable=False),
    sa.Column('tipo_apoyo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('empresarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('tipo_documento_personal', sa.String(length=10), nullable=False),
    sa.Column('numero_documento_personal', sa.String(length=30), nullable=False),
    sa.Column('numero_celular', sa.String(length=15), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=False),
    sa.Column('tipo_contribuyente', sa.String(length=20), nullable=False),
    sa.Column('numero_documento_contribuyente', sa.String(length=30), nullable=True),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('tamano', sa.String(length=20), nullable=False),
    sa.Column('sector_produccion', sa.String(length=100), nullable=False),
    sa.Column('sector_transformacion', sa.String(length=100), nullable=False),
    sa.Column('sector_comercializacion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit'),
    sa.UniqueConstraint('numero_documento_contribuyente'),
    sa.UniqueConstraint('numero_documento_personal'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('instituciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('tipo_institucion', sa.String(length=50), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('area_especializacion', sa.String(length=100), nullable=False),
    sa.Column('participacion_activa', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('inversionistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=30), nullable=False),
    sa.Column('numero_celular', sa.String(length=15), nullable=False),
    sa.Column('nombre_fondo', sa.String(length=150), nullable=True),
    sa.Column('tipo_inversion', sa.String(length=50), nullable=False),
    sa.Column('etapas_interes', sa.String(length=255), nullable=True),
    sa.Column('areas_interes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inversionistas')
    op.drop_table('instituciones')
    op.drop_table('empresarios')
    op.drop_table('emprendedores')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
