"""Creando tablas de dashboards limpia

Revision ID: ad83241b7fa3
Revises: 4e27382997cd
Create Date: 2025-12-16 09:55:07.811963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad83241b7fa3'
down_revision = '4e27382997cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discusiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discusion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_comentario', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discusion_id'], ['discusiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emprendedor_proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emprendedor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo_apoyo_buscado', sa.String(length=100), nullable=True),
    sa.Column('capital_requerido', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emprendedor_id'], ['emprendedores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresario_alianzas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_oferta', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresario_id'], ['empresarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresario_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('respuestas', sa.JSON(), nullable=True),
    sa.Column('puntaje_global', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresario_id'], ['empresarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresario_mercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empresario_id'], ['empresarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institucion_convocatorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.Column('publico_objetivo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institucion_noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('vistas', sa.Integer(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institucion_programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('duracion', sa.String(length=50), nullable=True),
    sa.Column('cupos_totales', sa.Integer(), nullable=True),
    sa.Column('cupos_ocupados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institucion_programas')
    op.drop_table('institucion_noticias')
    op.drop_table('institucion_convocatorias')
    op.drop_table('empresario_mercado')
    op.drop_table('empresario_diagnostico')
    op.drop_table('empresario_alianzas')
    op.drop_table('emprendedor_proyectos')
    op.drop_table('comentarios')
    op.drop_table('discusiones')
    # ### end Alembic commands ###
