"""Rename precio to celular

Revision ID: b04bf1731e53
Revises: ad83241b7fa3
Create Date: 2025-12-22 11:24:08.855978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b04bf1731e53'
down_revision = 'ad83241b7fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discusiones')
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comentarios_discusion_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresario_discusiones', ['discusion_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('empresario_mercado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular', sa.String(length=50), nullable=False))
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresario_mercado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('celular')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comentarios_discusion_id_fkey'), 'discusiones', ['discusion_id'], ['id'], ondelete='CASCADE')

    op.create_table('discusiones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('discusiones_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('discusiones_pkey'))
    )
    # ### end Alembic commands ###
